# common.mk — the make interface every one of these repositories answers to.
#
# GENERATED by `litkit mk`. Edit litkit and run `make mk-update`; edits made
# here are overwritten and, worse, make three repositories disagree again.
#
# Nine verbs, the same everywhere, whatever is underneath them:
#
#   make            sync + render — the "I just cloned this" path
#   make env        install from the lockfile
#   make sync       pull data/ and out/ from object storage
#   make build      run the pipeline: data/ -> out/
#   make render     reports/*.qmd -> the formats this repo publishes
#   make preview    live preview of one report
#   make check      tests and validators
#   make publish    push data/ and out/ to object storage (maintainer only)
#   make reproduce  the whole thing, from an empty checkout
#   make clean      remove derived files
#
# The one rule underneath them all: **the pipeline writes out/, and the
# documents only read it.** That is what lets `freeze: false` be the setting
# everywhere — a rendered report can never be quoting a stale number, because
# it has no cache to quote from and does no arithmetic of its own.
#
# A repository's own Makefile sets a few variables, includes this, and defines
# `build` and `check`. Everything else is here.

UV     := uv run
LITKIT := $(UV) litkit
Q      := $(UV) quarto

# Output formats for `make render`. gfm keeps a report readable and diffable
# in the repo; html is the one you send someone.
FORMATS ?= html

# Which report `make preview` and `make render-one` act on. The first one in
# reports/ unless you say otherwise: `make preview DOC=reports/OTHER.qmd`.
DOC ?= $(firstword $(wildcard reports/*.qmd))

# What `make reproduce` runs. A repo with expensive fetch stages lists them
# here, in order, instead of hiding them inside `build`.
REPRODUCE ?= env build render

# Extra paths for `make clean`, beyond the derived documents and scratch.
# Spliced into an `rm -rf`, so `clean` refuses anything absolute or containing
# `..` — repo-relative paths only.
CLEAN_EXTRA ?=

.DEFAULT_GOAL := default
.PHONY: default env sync status build render render-one preview check \
        publish reproduce clean clean-out mk-update doctor help

default: sync render  ## sync, then render — what a fresh clone runs

## ---- environment --------------------------------------------------------
# `uv sync` installs from the committed lockfile, so a second machine
# reproduces this one rather than approximating it. Rendering additionally
# needs the `quarto` binary on PATH; `make doctor` says so if it is missing.

env:  ## install the locked environment
	uv sync

doctor:  ## check the toolchain, the config and the credentials
	@$(LITKIT) doctor

## ---- data ---------------------------------------------------------------
# What moves, and whether it needs credentials, is declared in sync.toml.
# Where the bucket is public, `sync` needs no account anywhere.

sync:  ## pull data/ and out/ from object storage
	$(LITKIT) pull

# `litkit status` exits non-zero when the two differ, which is what you want in
# a script. Here it is a thing a person reads, so the difference is reported
# rather than raised — make's "Error 1" would say less than the table already
# does. Gate on `uv run litkit status` directly if you need the exit code.
status:  ## compare this checkout against the bucket, move nothing
	@$(LITKIT) status || echo "  differences above — 'make sync' pulls, 'make publish' pushes"

publish:  ## push data/ and out/ to object storage (maintainer only)
	$(LITKIT) push

## ---- the documents ------------------------------------------------------
# Every output is named after its source, and LITKIT_FORMAT tells document code
# which format it is being rendered into — the one hook a report needs to build
# a plain pipe table for markdown and a typeset one for HTML.

render: $(addprefix render-,$(FORMATS))  ## render every report, every format

render-%:
	LITKIT_FORMAT=$* $(Q) render --to $*

render-one: $(addprefix render-one-,$(FORMATS))  ## render just $(DOC)

render-one-%:
	LITKIT_FORMAT=$* $(Q) render $(DOC) --to $*

preview:  ## live preview of $(DOC)
	LITKIT_FORMAT=html $(Q) preview $(DOC) --to html

## ---- everything ---------------------------------------------------------

reproduce: $(REPRODUCE)  ## the whole thing, from an empty checkout

## ---- tidying ------------------------------------------------------------
# `clean` only removes what a render produces. Artifacts under out/ can be
# hours of computation and the bucket may be their only other copy, so
# `clean-out` is deliberately harder to run than typing four letters.

clean:  ## remove rendered documents and scratch
	@for p in $(CLEAN_EXTRA); do \
	   case "$$p" in /*|*..*) \
	     echo "CLEAN_EXTRA must be repo-relative: $$p" >&2; exit 1;; esac; \
	 done
	rm -rf .quarto _freeze reports/*_files reports/*.html $(CLEAN_EXTRA)
	find . -name __pycache__ -prune -exec rm -rf {} + 2>/dev/null || true

clean-out:  ## delete out/ — needs FORCE=1, and `make sync` to undo
ifndef FORCE
	@echo "out/ can be hours of computation, and the bucket may be its only"
	@echo "other copy. Check with \`make status\` first, then:"
	@echo "    make clean-out FORCE=1"
	@exit 1
endif
	rm -rf out

## ---- this file ----------------------------------------------------------

mk-update:  ## refresh common.mk from the installed litkit
	$(LITKIT) mk > common.mk
	@echo "common.mk refreshed — commit it"

help:  ## list the targets
	@awk 'BEGIN {FS = ":.*##"} \
	     /^[a-zA-Z][a-zA-Z0-9_-]*:.*##/ {printf "  %-14s %s\n", $$1, $$2}' \
	     $(MAKEFILE_LIST) | sort -u
